site_name: Pupsourcing
site_description: Clean Event Sourcing library for Go
site_author: getpup
site_url: https://getpup.github.io/pupsourcing-website

repo_name: getpup/pupsourcing
repo_url: https://github.com/getpup/pupsourcing

theme:
  name: null
  custom_dir: custom_theme

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Docs: docs-overview.md
  - About: about.md

markdown_extensions:
  admonition: { }
  codehilite:
    guess_lang: false
  toc:
    permalink: true
